package org.com.dev.carvel.sql;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import java.lang.reflect.Proxy;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class GeneratedKeyExecutorTest {

    private final SqlExecutor executor = new SqlExecutor();

    @Test
    void returnsGeneratedIntegerAndLongKeys () throws Exception {

        try (var connection = DriverManager.getConnection("jdbc:h2:mem:")) {

            executor.execute(connection, "CREATE TABLE integers (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, label VARCHAR)");
            executor.execute(connection, "CREATE TABLE longs (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, label VARCHAR)");
            assertEquals(1, executor.executeAndReturnGeneratedKey(connection, "INSERT INTO integers (label) VALUES ('first')"));
            assertEquals(2, executor.executeAndReturnGeneratedKey(connection, "INSERT INTO integers (label) VALUES ('second')"));
            assertEquals(1L, executor.executeAndReturnGeneratedKey(connection, "INSERT INTO longs (label) VALUES ('first')"));
            assertFalse(connection.isClosed());
        }
    }

    @Test
    void returnsNullWhenThereIsNoGeneratedKey () throws Exception {

        try (var connection = DriverManager.getConnection("jdbc:h2:mem:")) {

            executor.execute(connection, "CREATE TABLE plain (label VARCHAR)");
            assertNull(executor.executeAndReturnGeneratedKey(connection, "INSERT INTO plain VALUES ('value')"));
            assertEquals("value", executor.query(connection, "SELECT * FROM plain").get(0).get(0).getValue());
        }
    }

    @ParameterizedTest
    @ValueSource(strings = {"success", "executeUpdate", "getGeneratedKeys", "next", "getObject"})
    void closesOwnedResourcesOnSuccessAndAtEachFailurePoint (String failure) throws Exception {

        var closed = new ArrayList<String>();
        ResultSet result = (ResultSet) Proxy.newProxyInstance(getClass().getClassLoader(), new Class<?>[]{ResultSet.class}, (proxy, method, args) -> {

            if (method.getName().equals("close")) {

                closed.add("resultSet");

                return null;
            }

            if (method.getName().equals(failure)) {

                throw new SQLException("forced " + failure);
            }

            if (method.getName().equals("next")) {

                return true;
            }

            if (method.getName().equals("getObject")) {

                return 7;
            }

            throw new AssertionError("Unexpected ResultSet call: " + method.getName());
        });
        PreparedStatement statement = (PreparedStatement) Proxy.newProxyInstance(getClass().getClassLoader(), new Class<?>[]{PreparedStatement.class}, (proxy, method, args) -> {

            if (method.getName().equals("close")) {

                closed.add("statement");

                return null;
            }

            if (method.getName().equals(failure)) {

                throw new SQLException("forced " + failure);
            }

            if (method.getName().equals("executeUpdate")) {

                return 1;
            }

            if (method.getName().equals("getGeneratedKeys")) {

                return result;
            }

            throw new AssertionError("Unexpected statement call: " + method.getName());
        });
        Connection connection = (Connection) Proxy.newProxyInstance(getClass().getClassLoader(), new Class<?>[]{Connection.class}, (proxy, method, args) -> {

            if (method.getName().equals("prepareStatement")) {

                assertEquals("INSERT", args[0]);
                assertEquals(java.sql.Statement.RETURN_GENERATED_KEYS, args[1]);

                return statement;
            }

            throw new AssertionError("Connection belongs to caller: " + method.getName());
        });

        if (failure.equals("success")) {

            assertEquals(7, executor.executeAndReturnGeneratedKey(connection, "INSERT"));
        } else {

            assertEquals("forced " + failure, assertThrows(SQLException.class,
                    () -> executor.executeAndReturnGeneratedKey(connection, "INSERT")).getMessage());
        }

        boolean resultCreated = !failure.equals("executeUpdate") && !failure.equals("getGeneratedKeys");
        assertEquals(resultCreated ? List.of("resultSet", "statement") : List.of("statement"), closed);
    }

    @Test
    void propagatesSqlErrorsAndRetainsCallerConnection () throws Exception {

        try (var connection = DriverManager.getConnection("jdbc:h2:mem:")) {

            assertThrows(SQLException.class, () -> executor.executeAndReturnGeneratedKey(connection, "not SQL"));
            assertFalse(connection.isClosed());
            assertEquals(1, executor.query(connection, "SELECT 1").get(0).get(0).getValue());
        }
    }
}
