package org.com.dev.carvel.sql;

import org.com.dev.carvel.columnDefinition.ColumnDefinition;
import org.com.dev.carvel.query.LogicalOperator;
import org.com.dev.carvel.query.Operator;
import org.com.dev.carvel.query.QueryCondition;
import org.com.dev.carvel.query.QueryFilter;
import org.com.dev.carvel.row.Row;
import org.com.dev.carvel.table.Table;

import java.util.ArrayList;
import java.util.List;

public class SqlGenerator {

    private final TypeMapper typeMapper = new TypeMapper();

    public String createTable (Table table) {

        validateTable(table);

        StringBuilder sql = new StringBuilder();

        sql.append("CREATE TABLE ");
        sql.append(table.getName());
        sql.append(" (");

        List<ColumnDefinition> columns = table.getColumnDefinitions();

        for (int i = 0; i < columns.size(); i++) {

            ColumnDefinition column = columns.get(i);
            String columnSql = column.getName() + " " + typeMapper.map(column.getType());

            if (column.isGeneratedValue()) {

                columnSql = columnSql + " GENERATED BY DEFAULT AS IDENTITY";
            }

            if (column.isId()) {

                columnSql = columnSql + " PRIMARY KEY";
            }

            sql.append(columnSql);

            if (i < columns.size() - 1) {

                sql.append(", ");
            }
        }

        sql.append(");");

        return sql.toString();
    }

    private void validateTable (Table table) {

        if (table == null) {

            throw new IllegalArgumentException("Table cannot be null");
        }

        String tableName = table.getName();

        if (tableName == null || tableName.isBlank()) {

            throw new IllegalArgumentException("Table name cannot be null or blank");
        }

        List<ColumnDefinition> columns = table.getColumnDefinitions();

        if (columns == null) {

            throw new IllegalArgumentException("Table columns cannot be null");
        }

        if (columns.isEmpty()) {

            throw new IllegalArgumentException("Table requires at least one column");
        }

        List<String> seenColumns = new ArrayList<>();

        for (ColumnDefinition columnDefinition : columns) {

            if (columnDefinition == null) {

                throw new IllegalArgumentException("Table column cannot be null");
            }

            String columnName = columnDefinition.getName();

            if (columnName == null || columnName.isBlank()) {

                throw new IllegalArgumentException("Column name cannot be null or blank");
            }

            boolean duplicated = false;

            for (String seenColumn : seenColumns) {

                if (columnName.equalsIgnoreCase(seenColumn)) {

                    duplicated = true;
                }
            }

            if (duplicated) {

                throw new IllegalArgumentException("Duplicate column in table: " + columnName);
            }

            seenColumns.add(columnName);

            Class<?> javaType = columnDefinition.getType();

            if (javaType == null) {

                throw new IllegalArgumentException("Column type cannot be null");
            }

            typeMapper.map(javaType);
        }
    }

    public String insert (Table table, List<Row> rows) {

        if (table == null) {

            throw new IllegalArgumentException("Insert table cannot be null");
        }

        if (rows == null) {

            throw new IllegalArgumentException("Insert rows cannot be null");
        }

        if (rows.isEmpty()) {

            throw new IllegalArgumentException("Insert requires at least one row");
        }

        for (Row row : rows) {

            if (row == null) {

                throw new IllegalArgumentException("Insert row cannot be null");
            }

            if (row.getColumnName() == null || row.getColumnName().isBlank()) {

                throw new IllegalArgumentException("Column name cannot be null or blank");
            }
        }

        validateTable(table);

        StringBuilder sql = new StringBuilder();

        sql.append("INSERT INTO ");
        sql.append(table.getName());
        sql.append(" (");

        List<String> seenColumns = new ArrayList<>();

        for (Row row : rows) {

            boolean duplicated = false;

            for (String seenColumn : seenColumns) {

                if (row.getColumnName().equalsIgnoreCase(seenColumn)) {

                    duplicated = true;
                }
            }

            if (duplicated) {

                throw new IllegalArgumentException("Duplicate column in insert: " + row.getColumnName());
            }

            seenColumns.add(row.getColumnName());
        }

        for (Row row : rows) {

            boolean found = false;

            for (ColumnDefinition columnDefinition : table.getColumnDefinitions()) {

                if (row.getColumnName().equalsIgnoreCase(columnDefinition.getName())) {

                    found = true;

                    if (row.getValue() != null) {

                        SqlType expectedType = typeMapper.map(columnDefinition.getType());
                        SqlType receivedType = typeMapper.map(row.getValue().getClass());

                        if (expectedType != receivedType) {

                            throw new IllegalArgumentException("Invalid value type for column: " + row.getColumnName());
                        }
                    }
                }
            }

            if (!found) {

                throw new IllegalArgumentException("Column not found in table: " + row.getColumnName());
            }
        }

        for (int i = 0; i < rows.size();) {

            sql.append(rows.get(i).getColumnName());

            if (i < rows.size() - 1) {

                sql.append(", ");
            }

            i = i + 1;
        }

        sql.append(")");

        StringBuilder sqlValue = new StringBuilder();

        sqlValue.append(" VALUES (");

        for (int i = 0; i < rows.size();) {

            Object value = rows.get(i).getValue();

            if (value == null) {

                sqlValue.append("NULL");
            } else {

                SqlType sqlType = typeMapper.map(value.getClass());

                if (sqlType == SqlType.VARCHAR) {

                    String stringValue = value.toString();
                    stringValue = stringValue.replace("'", "''");

                    sqlValue.append("'");
                    sqlValue.append(stringValue);
                    sqlValue.append("'");
                } else {

                    sqlValue.append(value);
                }
            }

            if (i < rows.size() - 1) {

                sqlValue.append(", ");
            }

            i = i + 1;
        }

        sql.append(sqlValue);
        sql.append(");");

        return sql.toString();
    }

    public String selectAll (Table table) {

        if (table == null) {

            throw new IllegalArgumentException("Select table cannot be null");
        }

        if (table.getName() == null || table.getName().isBlank()) {

            throw new IllegalArgumentException("Table name cannot be null or blank");
        }

        return "SELECT * FROM " + table.getName() + ";";
    }

    public String selectById (Table table, Row idRow) {

        if (table == null) {

            throw new IllegalArgumentException("Select table cannot be null");
        }

        if (idRow == null) {

            throw new IllegalArgumentException("Select ID row cannot be null");
        }

        if (idRow.getColumnName() == null || idRow.getColumnName().isBlank()) {

            throw new IllegalArgumentException("Select ID column name cannot be null or blank");
        }

        if (idRow.getValue() == null) {

            throw new IllegalArgumentException("Select ID value cannot be null");
        }

        boolean idFound = false;

        for (ColumnDefinition columnDefinition : table.getColumnDefinitions()) {

            if (idRow.getColumnName().equalsIgnoreCase(columnDefinition.getName())) {

                idFound = true;
            }
        }

        if (!idFound) {

            throw new IllegalArgumentException("ID column not found in table: " + idRow.getColumnName());
        }

        StringBuilder sql = new StringBuilder();

        sql.append("SELECT * FROM ");
        sql.append(table.getName());
        sql.append(" WHERE ");
        sql.append(idRow.getColumnName());
        sql.append(" = ");

        Object idValue = idRow.getValue();
        SqlType idType = typeMapper.map(idValue.getClass());

        if (idType == SqlType.VARCHAR) {

            String stringValue = idValue.toString().replace("'", "''");

            sql.append("'");
            sql.append(stringValue);
            sql.append("'");
        } else {

            sql.append(idValue);
        }

        sql.append(";");

        return sql.toString();
    }

    public String update (Table table, List<Row> rows, Row idRow) {

        if (table == null) {

            throw new IllegalArgumentException("Update table cannot be null");
        }

        if (rows == null) {

            throw new IllegalArgumentException("Update rows cannot be null");
        }

        if (rows.isEmpty()) {

            throw new IllegalArgumentException("Update requires at least one row");
        }

        if (idRow == null) {

            throw new IllegalArgumentException("Update ID row cannot be null");
        }

        if (idRow.getColumnName() == null || idRow.getColumnName().isBlank()) {

            throw new IllegalArgumentException("Update ID column name cannot be null or blank");
        }

        boolean idFound = false;

        for (ColumnDefinition columnDefinition : table.getColumnDefinitions()) {

            if (idRow.getColumnName().equalsIgnoreCase(columnDefinition.getName())) {

                idFound = true;
            }
        }

        if (!idFound) {

            throw new IllegalArgumentException("ID column not found in table: " + idRow.getColumnName());
        }

        for (Row row : rows) {

            if (row.getColumnName().equalsIgnoreCase(idRow.getColumnName())) {

                throw new IllegalArgumentException("ID column cannot be updated: " + row.getColumnName());
            }
        }

        StringBuilder sql = new StringBuilder();

        sql.append("UPDATE ");
        sql.append(table.getName());
        sql.append(" SET ");

        for (int i = 0; i < rows.size();) {

            Row row = rows.get(i);

            sql.append(row.getColumnName());
            sql.append(" = ");

            Object value = row.getValue();

            if (value == null) {

                sql.append("NULL");
            } else {

                SqlType sqlType = typeMapper.map(value.getClass());

                if (sqlType == SqlType.VARCHAR) {

                    String stringValue = value.toString().replace("'", "''");

                    sql.append("'");
                    sql.append(stringValue);
                    sql.append("'");
                } else {

                    sql.append(value);
                }
            }

            if (i < rows.size() - 1) {

                sql.append(", ");
            }

            i = i + 1;
        }

        sql.append(" WHERE ");
        sql.append(idRow.getColumnName());
        sql.append(" = ");

        Object idValue = idRow.getValue();
        SqlType idType = typeMapper.map(idValue.getClass());

        if (idType == SqlType.VARCHAR) {

            String stringValue = idValue.toString().replace("'", "'");

            sql.append("'");
            sql.append(stringValue);
            sql.append("'");
        } else {

            sql.append(idValue);
        }

        sql.append(";");

        return sql.toString();
    }

    public String delete (Table table, Row idRow) {

        if (table == null) {

            throw new IllegalArgumentException("Delete table cannot be null");
        }

        if (idRow == null) {

            throw new IllegalArgumentException("Delete ID row cannot be null");
        }

        if (idRow.getValue() == null) {

            throw new IllegalArgumentException("Delete ID value cannot be null");
        }

        StringBuilder sql = new StringBuilder();

        sql.append("DELETE FROM ");
        sql.append(table.getName());
        sql.append(" WHERE ");
        sql.append(idRow.getColumnName());
        sql.append(" = ");

        Object idValue = idRow.getValue();
        SqlType idType = typeMapper.map(idValue.getClass());

        if (idType == SqlType.VARCHAR) {

            String stringValue = idValue.toString().replace("'", "''");

            sql.append("'");
            sql.append(stringValue);
            sql.append("'");
        } else {

            sql.append(idValue);
        }

        sql.append(";");

        return sql.toString();
    }

    public String selectBy (Table table, Row row, Operator operator) {

        String condition = buildCondition(table, row, operator);

        StringBuilder sql = new StringBuilder();

        sql.append("SELECT * FROM ");
        sql.append(table.getName());
        sql.append(" WHERE ");
        sql.append(condition);
        sql.append(";");

        return sql.toString();
    }

    public String selectByConditions (Table table, List<QueryCondition> conditions) {

        if (table == null) {

            throw new IllegalArgumentException("Select table cannot be null");
        }

        if (conditions == null) {

            throw new IllegalArgumentException("Select conditions cannot be null");
        }

        if (conditions.isEmpty()) {

            throw new IllegalArgumentException("Select requires at least one condition");
        }

        StringBuilder sql = new StringBuilder();

        sql.append("SELECT * FROM ");
        sql.append(table.getName());
        sql.append(" WHERE ");

        for (int i = 0; i < conditions.size();) {

            QueryCondition condition = conditions.get(i);

            if (condition == null) {

                throw new IllegalArgumentException("Query condition cannot be null");
            }

            Row row = new Row(condition.getColumnName(), condition.getValue());
            String conditionSql = buildCondition(table, row, condition.getOperator());

            sql.append(conditionSql);

            if (i < conditions.size() - 1) {

                sql.append(" AND ");
            }

            i = i + 1;
        }

        sql.append(";");

        return sql.toString();
    }

    public String selectByFilters (Table table, List<QueryFilter> filters) {

        if (table == null) {

            throw new IllegalArgumentException("Select table cannot be null");
        }

        if (filters == null) {

            throw new IllegalArgumentException("Select filters cannot be null");
        }

        if (filters.isEmpty()) {

            throw new IllegalArgumentException("Select requires at least one filter");
        }

        StringBuilder sql = new StringBuilder();

        sql.append("SELECT * FROM ");
        sql.append(table.getName());
        sql.append(" WHERE ");

        for (int i = 0; i < filters.size();) {

            QueryFilter filter = filters.get(i);

            if (filter == null) {

                throw new IllegalArgumentException("Query filter cannot be null");
            }

            QueryCondition condition = filter.getCondition();

            if (condition == null) {

                throw new IllegalArgumentException("Query condition cannot be null");
            }

            if (i > 0) {

                LogicalOperator logicalOperator = filter.getLogicalOperator();

                if (logicalOperator == null) {

                    throw new IllegalArgumentException("Logical operator cannot be null after the first condition");
                }

                if (logicalOperator == LogicalOperator.AND) {

                    sql.append(" AND ");
                } else if (logicalOperator == LogicalOperator.OR) {

                    sql.append(" OR ");
                }
            }

            Row row = new Row(condition.getColumnName(), condition.getValue());
            String conditionSql = buildCondition(table, row, condition.getOperator());

            sql.append(conditionSql);

            i = i + 1;
        }

        sql.append(";");

        return sql.toString();
    }

    private String buildCondition (Table table, Row row, Operator operator) {

        if (table == null) {

            throw new IllegalArgumentException("Select table cannot be null");
        }

        if (row == null) {

            throw new IllegalArgumentException("Select row cannot be null");
        }

        if (row.getColumnName() == null || row.getColumnName().isBlank()) {

            throw new IllegalArgumentException("Select column name cannot be null or blank");
        }

        if (operator == null) {

            throw new IllegalArgumentException("Select operator cannot be null");
        }

        boolean columnFound = false;

        for (ColumnDefinition columnDefinition : table.getColumnDefinitions()) {

            if (row.getColumnName().equalsIgnoreCase(columnDefinition.getName())) {

                columnFound = true;
            }
        }

        if (!columnFound) {

            throw new IllegalArgumentException("Column not found in table: " + row.getColumnName());
        }

        String sqlOperator;

        if (operator == Operator.EQUAL) {

            sqlOperator = "=";

        } else if (operator == Operator.NOT_EQUAL) {

            sqlOperator = "!=";

        } else if (operator == Operator.GREATER_THAN) {

            sqlOperator = ">";

        } else if (operator == Operator.LESS_THAN) {

            sqlOperator = "<";

        } else if (operator == Operator.GREATER_THAN_OR_EQUAL) {

            sqlOperator = ">=";

        } else if (operator == Operator.LESS_THAN_OR_EQUAL) {

            sqlOperator = "<=";

        } else {

            throw new IllegalArgumentException("Unsupported operator: " + operator);
        }

        StringBuilder condition = new StringBuilder();

        condition.append(row.getColumnName());

        Object value = row.getValue();

        if (value == null) {

            if (operator == Operator.EQUAL) {

                condition.append(" IS NULL");

            } else if (operator == Operator.NOT_EQUAL) {

                condition.append(" IS NOT NULL");

            } else {

                throw new IllegalArgumentException("Null values only support EQUAL or NOT_EQUAL");
            }
        } else {

            condition.append(" ");
            condition.append(sqlOperator);
            condition.append(" ");

            SqlType sqlType = typeMapper.map(value.getClass());

            if (sqlType == SqlType.VARCHAR) {

                String stringValue = value.toString().replace("'", "''");

                condition.append("'");
                condition.append(stringValue);
                condition.append("'");
            } else {

                condition.append(value);
            }
        }

        return condition.toString();
    }
}